### PR TITLE
User can see all bookings on MyBookings page

### PR DESCRIPTION
**Pull request by starphys**
This will include bookings that have already passed, but not bookings that have been cancelled (which should be deleted from the database).

### CODE REVIEW

**Review by BrendaCasas — APPROVED** [review]
Approved!

**Comment by starphys** [comment]
We also added change bookings feature to this since it was quick and directly related to the functioning of this page. Currently, every update changes the id of a reservation, need to fix that before merging.

**Review by elizabethhillman — APPROVED** [review]
looks good. note tho when booking reservations, I can have negative adults/children but otherwise approved

**Comment by aandrewt** [comment]
Looks good. Same comment as Liz where the input field allows negative values for adults and children. For the fields, I think putting in min="0" should help with the selection of the numbers, but for filtering inputs through a keyboard, I think that will need a new function to check if it's a number.

**Comment by starphys** [comment]
I agree with you both that this is a bug that should be addressed, but I'm going to merge this with the bug in it and we will demo around it if we don't get time to fix it before the demo.

**Pull request merged**
