### PR TITLE
Integrate payment reservation search

### PR DESCRIPTION
**Pull request by starphys**
Mega branch featuring a bunch of changes, I'm trying my best to document them.

Listings can be clicked to proceed with payment, reservation.
If user not logged in, redirect button to login.
Payment options are new card or saved card, saved card button only displays if user already has displayed cards.
  If user selects new card, payment page opens as component within the listing, allows user to put in data and click save/continue.
  If user selects saved card, ugly dropdown of card numbers lets them pick a card.
  If user clicks the listing, this resets.
Once payment is selected, reservation immediately displays. (currently unstyled).
If reservation is filled in correctly (as in no overlapping dates) then redirected to mybookings page.

Other changes:
Removed reservation and payment pages from app.js, navbar. 
User's saved payment loaded at login, unloaded at logout/delete account.

I apologize in advance for the complexity of this one, there are a lot of moving parts here and a lot of things to test. Please let me know if you spot bugs or opportunities for change.

### CODE REVIEW

**Comment by starphys** [comment]
I'm noticing one "bug" which doesn't really have a fix. If we make enough changes to this while editing, sometimes top level state unloads, causing issues when the reservation component tries to render. This should not happen in production, just when changes are being made to the underlying react/html/css files.

**Review by aandrewt — CHANGES_REQUESTED** [review]
The button to pay with a saved card does not show up as intended

**Comment by starphys** [comment]
Updated branch to fix the bug @FreezingTide pointed out, as well as some strange behavior in the reservation feature.

**Review by BrendaCasas — APPROVED** [review]
Everything is working correctly, well done!

**Review by aandrewt — APPROVED** [review]
Great work

**Pull request merged**
