### PR TITLE
User accounts

### PR DESCRIPTION
**Pull request by vanessaucey**
The sign-up page is implemented on both the back-end and front-end.

### CODE REVIEW

**Review by starphys — CHANGES_REQUESTED** [review]
Overall, this is excellent. It's really exciting to see the data persist in the database, and the overall look and feel of the signup page is nice. There are a few changes we should definitely make now, and some we could make now or could make a task in the next sprint:

Fix before merging:
Remove .DS_store and the React logos, replace the React logos with SpartanStay logos. 

For the signup feature itself, there is no confirmation to the user that they successfully signed up, it looks like the button doesn't do anything and the form doesn't change. Some sort of success message would be great. 

Could fix now or in the next sprint:
We need to have some level of string checking for our email field, and some sort of comparison for the password field. 
Response from the backend if there is already a user with this email address (don't make the account in this case). 
Passwords should be hashed into the database, and the same hashing algorithm should be used for the login logic.
Consider if we should allow spaces in first name or last name field.

**Comment by elizabethhillman** [comment]
I'm assuming this is the same thing that Evan meant regarding password comparison but making sure password==comfirmPassword. right now it just takes whatever is in password. It would be nice if once you click sign-up button and it's successful, all the fields go back to blank

**Comment by starphys** [comment]
Updated with some of the changes I requested, fixed some syntax errors to make the password check genuinely block account creation. The alert for passwords is just plain text rn, the fix is to include the bootstrap CSS, but that breaks our other CSS. A good work around might be defining our own CSS for the bootstrap Alert component.

**Review by starphys — APPROVED** [review]

**Comment by LovepreetUppal** [comment]
All errors are fixed
Functioning as expected

**Review by LovepreetUppal — APPROVED** [review]
No errors
Feature working as expected

**Pull request merged**
