### PR TITLE
Reservation

### PR DESCRIPTION
**Pull request by aandrewt**

### CODE REVIEW

**Comment by elizabethhillman** [comment]
Should add a method that will find all reservations for one certain user

**Comment by elizabethhillman** [comment]
make sure user can't make reservation on same day at two+ different hotels

**Comment by starphys** [comment]
Okay, I made a few updates here that should get good performance out of the backend in terms of response time (even with a lot of reservations in the system) and a few small changes to frontend to make passing data and retrieving the response from backend a little simpler. If you guys are good with these changes, this branch is ready to merge as far as I'm concerned.

**Comment by starphys** [comment]
Replace the text in Home.js with the following to test this in frontend. You'll need to manually tweak parameters listed in token, payment, or the hotelId in this file directly to see different responses from the backend, mostly because this feature is supposed to be a child of another feature that would programmatically feed that data to it.
```js
import logo from '../images/logo-1.png';
import Reservation from "../components/Reservation"
import "../styles.css";
import { useState } from 'react';

function Home() {
  const [success, setSuccess] = useState(false)
  const token = {
    id:1,
    email:"email@website.com",
    firstName:"Ian",
    lastName:"van Dyke",
  }
  const payment = {
    cardNum:1111111111111111,
    expDate:"2022-12-25",
    securityCode:808,
    address:"123 Here Street, AK USA"
  }
  return (
    <div className="Home">
      <header className="App-header">
        <img src={logo} className="App-logo" alt='logo'/>
        <p>
            <h1>Welcome to SpartanStay</h1>
        </p>
        <Reservation token={token} payment={payment} hotelId={4} setSuccess={setSuccess}/>
        {success ? "YOU DID IT" : ""}
        <a
          className="App-link"
          href="https://google.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          About US
        </a>
      </header>
    </div>
  );
}
export default Home;```

**Comment by elizabethhillman** [comment]
back end code looks good. A few notes: 1) for adding phone numbers, we could make it so the user can only input 10 ints, currently, I can add as many numbers as I want. 2) when i click the "book" button, nothing happens

**Review by elizabethhillman — APPROVED** [review]
back end code looks good. A few notes: 1) for adding phone numbers, we could make it so the user can only input 10 ints, currently, I can add as many numbers as I want. 2) when I click the "book" button, nothing happens

**Review by starphys — APPROVED** [review]

**Pull request merged**
