### PR TITLE
Cancellation page displays from navbar

### PR DESCRIPTION
**Pull request by starphys**
Software by Mohib/Ece, copy by Evan

### CODE REVIEW

**Comment by starphys** [comment]
@Mohib1402 @ecegulden I saw a branch for this has been open on here for about 2 weeks, I tried to rebase it but it has a bunch of polluting commits so I just moved the work to a new branch for merging. Let me know if I missed anything, but I'm pretty sure this can be merged as is.

**Review by elizabethhillman — APPROVED** [review]
This looks very nice! good to merge

**Comment by LovepreetUppal** [comment]
Looks good

**Review by LovepreetUppal — APPROVED** [review]
looks good

**Pull request merged**
